language: php

addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13

services:
  - mysql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.3
 - 7.4
 - 8.0

env:
 global:
  - PGVER=13
  - MOODLE_BRANCH=MOODLE_39_STABLE
  - MOODLE_BRANCH=MOODLE_311_STABLE
  - MOODLE_BRANCH=MOODLE_401_STABLE
 matrix:
  - DB=pgsql
  - DB=mysqli

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} -gt 7 ]]; then pecl install xmlrpc-beta; fi
  - echo 'max_input_vars=5000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Don't disable xdebug if you want to get it used for code coverage.
  - phpenv config-rm xdebug.ini
  # Alternative (for Moodle 3.10 and up) is to use pcov. It can be installed using:
  # - pecl install pcov
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpdoc --fail-on-warning
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
